bhauman/figwheel-main

README.md, docs/README.md, docs/docs/create_a_build.md, docs/docs/your_own_page.md, docs/getting_help.md, docs/tutorial.md, helper-content/missing_index.md, src/figwheel/main.cljc, src/figwheel/main/helper.cljc, src/figwheel/main/schema/config.clj
Mostly just fixing typos in documentation
=> copy fixes

src/figwheel/main/schema/config.clj, src/figwheel/main/schema/core.clj
Missing copy fixes from previous merge and some more
=> more copy fixes

docs/docs/vim.md
Here's my first attempt at documenting how to setup a multi-REPL workflow.  I'm very open to feedback - too much detail, not enough, etc.?
=> REPL Workflow doc

docs/docs/hot_reloading.md
I've tried to add as many Google-friendly variations as possible :) -- and also make the `^:figwheel-hooks` explicit as it's easy to miss when skimming...
=> Add note about rerendering with Reagent et al.

docs/docs/compile_config.md
edit of https://figwheel.org/docs/compile_config.html
=> fix typo in docs

docs/docs/compile_config.md
Did a wee bit of editing (typos, punctuation etc)
=> Fixed typos.

docs/docs/main_script.md
Fixed typos spotted in the docs.
=> Fixed some typos

docs/docs/advanced_compile.md, docs/docs/background_builds.md, docs/docs/compile_config.md, docs/docs/extra_mains.md, docs/docs/hot_reloading.md, docs/docs/reloadable_code.md, docs/docs/scripting_api.md, docs/docs/testing.md, docs/docs/your_own_page.md
Some of the whitespace removal was done by emacs.
If you disagree with any of these changes, I'm happy to revise.
=> Spelling, grammar, whitespace removal

docs/docs/classpaths.md
Found a typo. Thanks for the thorough documentation!
=> Fix project.clj reference for leiningen in classpaths.md

src/figwheel/main/css_reload.cljc
Hi Bruce, hope your holidays are going well! This is the PR for issue #129. It uses the minimal method you requested.
The behavior is the same except in how it determines the link to reload. Now, when a CSS file changes, it looks it up in `goog.cssom/getAllCssStyleSheets` to verify it's in the HTML file, then uses `.-parentStylesheet` to go up the hierarchy until it finds the top-level link. The top-level link is replaced as normal.
Also, I hope you don't mind, but I updated the code to switch from removing the old link after a 300ms timeout to removing it after the new link's `load` event fires (at which point all CSS files, including children, have been loaded and parsed). This is 10-20x faster, with no loss of functionality. I checked some old browsers (IE10, Safari 5), and it should …
=> Handle CSS @imports

helper-content/repl_welcome.md
Sorry to do another PR, this one is from my phone.
=> Micro typo

src/figwheel/main/schema/config.clj
looks like an old docstring that needs to be updated.
Will this update the docs on the website, or is that a separate PR?
=> fix :figwheel => :figwheel-core

doc/figwheel-main-options.md
Hello, I was wondering if "src/cljs" was the intended file path? Not sure where "cljs-src" comes from...
=> Updating :watch-dirs example

docs/docs/installation.md
removed "is" from the sentence "This simplicity is also means that...."
=> fix typo in installation.md

docs/config-options.md, docs/docs/background_builds.md, docs/docs/build_inputs.md, docs/docs/classpaths.md, docs/docs/create_a_build.md, docs/docs/editor-integration.md, docs/docs/emacs.md, docs/docs/extra_mains.md, docs/docs/jetty_conflicts.md, docs/docs/npm.md, docs/docs/reloadable_code.md, docs/docs/ring-handler.md, docs/docs/testing.md
As I was reading through Figwheel's documentation (which was very helpful!), I noticed some mistakes here and there. This PR corrects a number of these errors.
=> Correct errors in the documentation

docs/docs/react-native.md
Congratulations for making this bridging work happen.
I followed the guide step by step and bumped into this issue.
=> Improve react native guide

deps.edn, doc/figwheel-main-options.md, docs/config-options.md, project.clj, src/figwheel/main.cljc, src/figwheel/main/css_reload.cljc, src/figwheel/main/schema/config.clj, src/figwheel/main/watching.clj
In my testing this cuts out a 6 second delay for reloading
=> fix#298 Detect file changes much faster

docs/docs/installation.md
As documented here: https://clojure.org/guides/getting_started#_installation_on_mac_via_homebrew
=> Docs for brew install updated to use official tap

docs/docs/create_a_build.md
Replaced `clojure -A:fig -b dev -r ` with `clojure -M:fig -b dev -r`
=> Replace -A with -M

docs/docs/installation.md
=> Updated Alias option

docs/docs/npm.md
Moving the space between the options instead of inside the string
=> Small whitespace tweak
