bhauman/figwheel-main

README.md
docs/README.md

I think I had this fix in a previous pull request but just noticing that there are three copies of README.md.  Curious why it's like this?  Maybe you have a script to update the other two based on the one in the root?
I guess you're not doing this for a reason but why not commit the duplicated readme's as symbolic links?

copy fixes

---

src/figwheel/main/css_reload.cljc

The DOM may contain preload link elements with the same href as a
stylesheet we're attempting to reload, e.g.:
```
<link rel="preload"    href="style.css">
<link rel="stylesheet" href="style.css">
```
Ignore these to make sure we update the stylesheet instead of the preload.

Ignore preload link elements on css reload

---

docs/docs/testing.md

Properly quotes arguments if they contain `*` or whitespace. Also allows multiple arguments to be passed to `headless-chrome`.

Safer bash scripting

---

docs/docs/live_css.md
helper-content/css_reloading.md
helper-resources/public/com/bhauman/figwheel/helper/content/css_reloading.html

The documentation is at https://figwheel.org/docs/your_own_page, but links point to your_**host**_page.

Fix broken links to Host Page documentation

---

docs/docs/cursive.md

This covers getting figwheel-main started using Leiningen for CLJS projects - I'm planning to add a section for combined CLJ and CLJS projects next.
CLI integration with Cursive is quite new and does not work with figwheel-main at this point, but I expect it will be fixed in the next EAP or full release (latest is 1.8.0-eap7) and I plan to add documentation for that once it is working.

First attempt at Cursive specific documentation

---

helper-content/server_only_welcome.md
helper-resources/public/com/bhauman/figwheel/helper/content/server_only_welcome.html
src/figwheel/main.cljc
src/figwheel/main/schema/cli.clj

The option was called `--serve`, but the documentation referred to `--server`.

Fix documentation for --serve CLI argument

---

docs/docs/classpaths.md

The section *"Adding the `cljs-src` path with CLI Tools"* ends with *"Inspecting the new classpath"*, but mentioning `cljs-dev` instead of `cljs-src` as the example dir that was meant to be added to the classpath.  This commit fixes that.

Fix minor typo in docs/docs/classpaths.md

---

src/figwheel/main/css_reload.cljc

instead of paths 'relativized' from working directory.
This fixes css reloading when canonicalized :css-dirs are outside of
the working directory.
It's ok to use the entire absolute path for file names to reload, since
the figwheel client locates css link tags to replace by matching reversed
lists of path segments (see figwheel.main.css-reload/matches-file?).

Use canonical paths for css reload

---

docs/docs/cursive.md

I mistakenly assumed the `dev` folder would need to be in my `src` folder, as it contains a .clj file.

Small clarification in Cursive integration docs

---

docs/docs/build_inputs.md
docs/docs/classpaths.md
docs/docs/code_splitting.md
docs/docs/compile_config.md
docs/docs/cursive.md
docs/docs/editor-integration.md
docs/docs/emacs.md
docs/docs/getting_help.md
docs/docs/hot_reloading.md
docs/docs/installation.md
docs/docs/jetty_conflicts.md
docs/docs/main_script.md
docs/docs/npm.md
docs/docs/reloadable_code.md
docs/docs/ring-handler.md
docs/docs/scripting_api.md
docs/docs/testing.md
docs/docs/vim.md
docs/docs/your_own_page.md

I found the docs an excellent resource to learn the figwheel-main. While reading them I stumbled upon a few typos that I fixed in this pull request.

Fix typos in docs

---

docs/docs/vim.md

Yes, starting the repl first _is_ implied in these docs and the repl-env docstring.
The trouble for me came in that it seems Piggieback sometimes will and sometimes won't start up a cljs-repl on its own given a repl-env. I got to assuming that `:Piggieback (figwheel.main.api/repl-env "dev")` in vim was roughly equivalent to starting the cljs-repl in the clj-repl.
I'm presuming others might run into this confusion, and want to make the right thing to do more explicit.

Adds a proposed emphatic note to the Vim help

---

docs/docs/classpaths.md

Was going through docs and noticed a small typo.

Fix a small typo in documentation

---

src/figwheel/main.cljc
src/figwheel/main/css_reload.cljc

Hawk Options are now being passed through the css reload start watch
which was breaking polling options.
Fixes Issue #207

Add Hawk Options to CSS watcher

---

docs/docs/your_own_server.md

The complaints are that figwheel does not start. I figure that the (run-jetty) call is blocking. So either put the whole call in a (future) or change the :join? to false. Not sure which is better or any implication. For your consideration.

Issues #169 #213 figwheel does not start

---

project.clj
src/figwheel/main.cljc

Hi!
As #227 issue explans, figwheel is broken with latest version of expound. This change should fix it.

Update expound and fix incompatibilities.

---

docs/docs/npm.md

I believe the top line of the last javascript code block will not work with `{goog = window}` and instead needs to be `{goog: window}`. At least that's how I had to do it when testing in the browser console. I'm guessing it's just a typo, but I could be misunderstanding something.

Fix typo and javascript code sample

---

docs/docs/installation.md

The CLI Tools are available on Windows now in an alpha state. I've used the CLI Tools on Windows for the Figwheel tutorial and it's been working fine. Since it's currently in an alpha state I don't know if you want to remove the section "On Windows" or just change it to something like I did.

Change note about CLI Tools on Windows

---

docs/docs/advanced_compile.md

Improved throubleshooting section by adding a link to a blog post that summarizes common techniques for avoiding and fixing advanced compilation bugs.

Add a new link to Advanced Compile throubleshooting section

---

docs/docs/npm.md

final-ouitput-dir > final-output-dir
\*global > \*global\*

fix typo in npm docs

---

deps.edn

Root cause is an unfixed bug introduced into ClojureScript.
devtools has a workaround.
Updating to 1.05

fix #314: avoid false warnings by bump devtools

---

src/figwheel/main.cljc

A fix related to https://github.com/bhauman/figwheel-main/issues/317
Since figwheel already handles running the :bundle-cmd, it's unnecessary to pass that option again to cljs compiler to re-run the command.

Don't pass :bundle-cmd to compiler-env

---

docs/config-options.md

It's closure-defines, not clojure-defines
And I'm sure that's the first and last time anyone ever will make that mistake!

Fix typo in config property

---

docs/config-options.md

Reverts bhauman/figwheel-main#326
Yeah this shouldn't be fixed here. As the top of the page states this file is generated from another file.  `src/figwheel/main/schema/core.clj`

Revert "Fix typo in config property"

---

docs/docs/code_splitting.md

This PR fixes the following two things:
**Incorrect script paths in `Index.html`**
Figwheel serves the static files from the `target/public/` folder so the
`target` prefix in the `target/cljs-out/*.js` script src paths are incorrect.
This commit fixes the script paths in the index.html host page so the browser
doesn't show 404 responses for the compiled js files.
**`goog.dom.createDom` error in cljs 1.11+**
The `goog.dom/createDom` function requires a second argument of
`opt_attributes`.  (See official documentation at
https://google.github.io/closure-library/api/goog.dom.html.)  In previous
ClojureScript versions, the `goog.dom/createDom` function was able to handle the
nonexistence of `opt_attributes` argument, miraculously.  However, with
ClojureScript 1.11.60, this is considered an …

Fix Code Splitting example for ClojureScirpt 1.11+
